Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,6 +21,20 @@ jobs:
     - name: Test the application
       run: python -m unittest discover
 
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
+
+    - name: Log in to Docker Hub (or AWS ECR)
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+
+    - name: Build and Push Docker Image
+      run: |
+        docker build -t your-docker-repo/app:latest .
+        docker push your-docker-repo/app:latest
+
     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.4
       with:
@@ -29,9 +43,9 @@ jobs:
     - name: Deploy and Restart Application
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-          cd /home/ubuntu/task-9|| { echo "Directory not found"; exit 1; }
-          docker build -t app .
+          cd /home/ubuntu/task-9 || { echo "Directory not found"; exit 1; }
+          docker pull your-docker-repo/app:latest
           docker stop app-container || true
           docker rm app-container || true
-          docker run -d -p 80:5000 --name app-container app
+          docker run -d -p 80:5000 --name app-container your-docker-repo/app:latest
         EOF
